# Default configuration

spring:
    profiles:
        active: dev
    main:
        banner-mode: "off"
custom:
    system:
        length: 100
        particles: 1000
        interaction-radius: 2.5
    simulation:
        iterations: 500
        eta: 1.5
        M: 10
        speed-module: 0.03

---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development


logging:
    config: classpath:logging/logback-spring-dev.xml

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production

logging:
    config: classpath:logging/logback-spring-prod.xml